[Remap]
x = x
y = y
z = z
a = a
b = b
c = c
s = s

[Command]
name = "CPU1" ;<------------------------(AI Command Name)
command = U, D, F, U, D, F ;<------------(Command combination)
time = 0

[Command]
name = "CPU2"
command = U, B, F, U, D, F
time = 0

[Command]
name = "CPU3"
command = U, D, D, U, D, F
time = 0

[Command]
name = "CPU4"
command = U, F, U, B, U, D, F
time = 0

[Command]
name = "CPU5"
command = B, B, B, U, B, U, D, F
time = 0

[Command]
name = "CPU6"
command = U, D, B, U, B, U, D, F
time = 0

[Command]
name = "CPU7"
command = F, F, B, U, B, U, D, F
time = 0

[Command]
name = "CPU8"
command = U, D, U, U, B, U, D, F
time = 0

[Command]
name = "CPU9"
command = F, B, B, U, B, U, D, F
time = 0

[Command]
name = "CPU10"
command = F, F, B, B, U, B, U, D, F
time = 0

[Command]
name = "CPU11"
command = D, D, D, D, D, D, D, D, D
time = 0

[Command]
name = "CPU12"
command = F, F
time = 0

[Command]
name = "CPU13"
command = B, B, B, B, B, B, B
time = 0

[Command]
name = "CPU14"
command = F, D, DF, x
time = 1

[Command]
name = "CPU15"
command = F, D, DF, y
time = 1

[Command]
name = "CPU16"
command = F, D, DF, z
time = 1

[Command]
name = "CPU17"
command = D, D, D, D, D, D, D, D, D
time = 1

[Command]
name = "CPU18"
command = B, B, B, B, B, B, B
time = 1

[Command]
name = "CPU19"
command = F, D,DF, F,y,x,x,x,x
time = 1

[Command]
name = "CPU20"
command = F, D,DF, F,y,x,x,x,y
time = 1

[Command]
name = "CPU21"
command = F, D,DF, F,y,x,x,y,x
time = 1

[Command]
name = "CPU22"
command = F, D,DF, F,y,x,y,x,x
time = 1

[Command]
name = "CPU23"
command = F, D,DF, F,y,y,x,x,x
time = 1

[Command]
name = "CPU24"
command = F, D,DF, F,a,x,x,x,x
time = 1

[Command]
name = "CPU25"
command = F, D,DF, F,a,x,x,x,y
time = 1

[Command]
name = "CPU26"
command = F, D,DF, F,a,x,x,y,x
time = 1

[Command]
name = "CPU27"
command = F, D,DF, F,a,x,y,x,x
time = 1

[Command]
name = "CPU28"
command = F, D,DF, F,a,y,x,x,x
time = 1

[Command]
name = "CPU29"
command = F, D,DF, F,y,x,x,x,a
time = 1

[Command]
name = "CPU30"
command = F, D,DF, F,y,x,x,a,x
time = 1

[Command]
name = "CPU31"
command = F, D,DF, F,y,x,a,x,x
time = 1

[Command]
name = "CPU32"
command = F, D,DF, F,y,a,x,x,x
time = 1

[Command]
name = "CPU33"
command = F, D,DF, F,a,a,x,x,x
time = 1

[Command]
name = "CPU34"
command = F, D,DF, F,b,x,x,x,x
time = 1

[Command]
name = "CPU35"
command = F, D,DF, F,b,x,x,x,y
time = 1

[Command]
name = "CPU36"
command = F, D,DF, F,b,x,x,y,x
time = 1

[Command]
name = "CPU37"
command = F, D,DF, F,b,x,y,x,x
time = 1

[Command]
name = "CPU38"
command = F, D,DF, F,b,y,x,x,x
time = 1

[Command]
name = "CPU39"
command = F, D,DF, F,y,x,x,x,b
time = 1

[Command]
name = "CPU40"
command = F, D,DF, F,y,x,x,b,x
time = 1

[Command]
name = "CPU41"
command = F, D,DF, F,y,x,b,x,x
time = 1

[Command]
name = "CPU42"
command = F, D,DF, F,y,b,x,x,x
time = 1

[Command]
name = "CPU43"
command = F, D,DF, F,b,b,x,x,x
time = 1


[Command]
name = "CPU44"
command = F, D,DF, F,b,x,x,x,x
time = 1

[Command]
name = "CPU45"
command = F, D,DF, F,b,x,x,x,y
time = 1

[Command]
name = "CPU46"
command = F, D,DF, F,b,x,x,y,x
time = 1

[Command]
name = "CPU47"
command = F, D,DF, F,b,x,y,x,x
time = 1

[Command]
name = "CPU48"
command = F, D,DF, F,b,y,x,x,x
time = 1

[Command]
name = "CPU49"
command = F, D,DF, F,y,x,x,x,b
time = 1

[Command]
name = "CPU50"
command = F, D,DF, F,y,x,x,b,x
time = 1

[Command]
name = "CPU51"
command = F, D,DF, F,y,x,b,x,x
time = 1

[Command]
name = "CPU52"
command = D, D, D, D, D, D, D, D, D
time = 1

[Command]
name = "CPU53"
command = B, B, B, B, B, B, B
time = 1


[Command]
name = "CPU54"
command = F, D,DF, F,b,x,x,x,x
time = 1

[Command]
name = "CPU55"
command = F, D,DF, F,b,x,x,x,y
time = 1

[Command]
name = "CPU56"
command = F, D,DF, F,b,x,x,y,x
time = 1

[Command]
name = "CPU57"
command = F, D,DF, F,b,x,y,x,x
time = 1

[Command]
name = "CPU58"
command = F, D,DF, F,b,y,x,x,x
time = 1

[Command]
name = "CPU59"
command = F, D,DF, F,y,x,x,x,b
time = 1

[Command]
name = "CPU60"
command = F, D,DF, F,y,x,x,b,x
time = 1

[Command]
name = "CPU61"
command = F, D,DF, F,y,x,b,x,x
time = 1

[Command]
name = "CPU62"
command = F, D,DF, F,y,b,x,x,x
time = 1

[Command]
name = "CPU63"
command = F, D,DF, F,b,b,x,x,x
time = 1

;-| Default Values |-------------------------------------------------------
[Defaults]
; Default value for the "time" parameter of a Command. Minimum 1.
command.time = 15

; Default value for the "buffer.time" parameter of a Command. Minimum 1,
; maximum 30.
command.buffer.time = 1


;-| Super Motions |--------------------------------------------------------
;The following two have the same name, but different motion.
;Either one will be detected by a "command = TripleKFPalm" trigger.
;Time is set to 20 (instead of default of 15) to make the move
;easier to do.
;

;-----------Hypers-------------

[Command]
name = "MeteorSmasher"
command = ~F, D, DF, x+y
time = 20

[Command]
name = "MeteorSmasher"
command = ~F, D, F, x+y
time = 20

[Command]
name = "MeteorSmasher"
command = ~F, D, DF, y+z
time = 20

[Command]
name = "MeteorSmasher"
command = ~F, D, F, y+z
time = 20

[Command]
name = "MeteorSmasher"
command = ~F, D, DF, x+z
time = 20

[Command]
name = "MeteorSmasher"
command = ~F, D, F, x+z
time = 20

[Command]
name = "KryptonianCrusher"
command = ~D, DB, B, x+y
time = 20

[Command]
name = "KryptonianCrusher"
command = ~D, DB, B, y+z
time = 20

[Command]
name = "KryptonianCrusher"
command = ~D, DB, B, x+z
time = 20

[Command]
name = "KryptonianCrusher"
command = ~D, B, x+y
time = 20

[Command]
name = "KryptonianCrusher"
command = ~D, B, y+z
time = 20

[Command]
name = "KryptonianCrusher"
command = ~D, B, x+z
time = 20

[Command]
name = "SolarAnnihilation"
command = ~D, DB, B, a+b
time = 15

[Command]
name = "SolarAnnihilation"
command = ~D, B, a+b
time = 15

[Command]
name = "SolarAnnihilation"
command = ~D, DB, B, b+c
time = 15

[Command]
name = "SolarAnnihilation"
command = ~D, B, b+c
time = 15

[Command]
name = "SolarAnnihilation"
command = ~D, DB, B, a+c
time = 15

[Command]
name = "SolarAnnihilation"
command = ~D, B, a+c
time = 15

[Command]
name = "UpInTheClouds"
command = ~D,F,a+b
time = 20

[Command]
name = "UpInTheClouds"
command = ~D,DF,F,a+b
time = 20

[Command]
name = "UpInTheClouds"
command = ~D,F,b+c
time = 20

[Command]
name = "UpInTheClouds"
command = ~D,DF,F,b+c
time = 20

[Command]
name = "UpInTheClouds"
command = ~D,F,a+c
time = 20

[Command]
name = "UpInTheClouds"
command = ~D,DF,F,a+c
time = 20

[Command]
name = "HyperHeatVision"
command = ~D,F,x+y
time = 20

[Command]
name = "HyperHeatVision"
command = ~D,DF,F,x+y
time = 20

[Command]
name = "HyperHeatVision"
command = ~D,F,y+z
time = 20

[Command]
name = "HyperHeatVision"
command = ~D,DF,F,y+z
time = 20

[Command]
name = "HyperHeatVision"
command = ~D,F,x+z
time = 20

[Command]
name = "HyperHeatVision"
command = ~D,DF,F,x+z
time = 20

[Command]
name = "FasterThanSpeedingBullet"
command = ~40$B,F,a+b
time = 20

[Command]
name = "FasterThanSpeedingBullet"
command = ~40$B,F,b+c
time = 20

[Command]
name = "FasterThanSpeedingBullet"
command = ~40$B,F,a+c
time = 20

;-----------Specials-------------

[Command]
name="Roll"
command= ~D, DF, F, a
time=20
[Command]
name="Roll"
command= ~D, DF, F, b
time=20
[Command]
name="Roll"
command= ~D, DF, F, c
time=20
[Command]
name="Roll"
command= ~D, DF, F, x
time=20
[Command]
name="Roll"
command= ~D, DF, F, y
time=20
[Command]
name="Roll"
command= ~D, DF, F, z
time=20

[Command]
name = "SoaringJustice"
command = ~F, D, DF, x
time = 20

[Command]
name = "SoaringJustice"
command = ~F, D, F, x
time = 20

[Command]
name = "SoaringJustice"
command = ~F, D, DF, y
time = 20

[Command]
name = "SoaringJustice"
command = ~F, D, F, y
time = 20

[Command]
name = "SoaringJustice"
command = ~F, D, DF, z
time = 20

[Command]
name = "SoaringJustice"
command = ~F, D, F, z
time = 20

[Command]
name = "SuperSpeed"
command = ~40$B,F,a
time = 20

[Command]
name = "SuperSpeed2"
command = ~40$B,F,b
time = 20

[Command]
name = "SuperSpeed3"
command = ~40$B,F,c
time = 20

[Command]
name = "HeatVision1"
command = ~D, DF, F, x
time = 15

[Command]
name = "HeatVision1"
command = ~D, F, x
time = 15

[Command]
name = "HeatVision2"
command = ~D, DF, F, y
time = 15

[Command]
name = "HeatVision2"
command = ~D, F, y
time = 15

[Command]
name = "HeatVision3"
command = ~D, DF, F, z
time = 15

[Command]
name = "HeatVision3"
command = ~D, F, z
time = 15

[Command]
name = "ColdBreath"
command = ~D, F, a
time = 15

[Command]
name = "ColdBreath"
command = ~D, DF, F, a
time = 15

[Command]
name = "ColdBreath2"
command = ~D, F, b
time = 15

[Command]
name = "ColdBreath2"
command = ~D, DF, F, b
time = 15

[Command]
name = "ColdBreath2"
command = ~D, F, c
time = 15

[Command]
name = "ColdBreath2"
command = ~D, DF, F, c
time = 15

[Command]
name = "SolarFlare"
command = ~D, DB, B, a
time = 15

[Command]
name = "SolarFlare"
command = ~D, B, a
time = 15

[Command]
name = "SolarFlare"
command = ~D, DB, B, b
time = 15

[Command]
name = "SolarFlare"
command = ~D, B, b
time = 15

[Command]
name = "SolarFlare"
command = ~D, DB, B, c
time = 15

[Command]
name = "SolarFlare"
command = ~D, B, c
time = 15

[Command]
name = "DU"
command = D, U
time = 10

[Command]
name = "DU"
command = D, UF
time = 10

[Command]
name = "DU"
command = D, UB
time = 10

;---------Throws---------------

[Command]
name = "ThrowHyperBreath"
command = /$F, c
time = 2

;[Command]
;name = "KarateToss"
;command = /$F, c
;time = 2

;[Command]
;name = "BackToss"
;command = /$B, z
;time = 2

;[Command]
;name = "BackKarateToss"
;command = /$B, c
;time = 2

;-----------Dash-------------

[Command]
name = "FF"       ;Required (do not remove)
command = F, F
time = 10

[Command]
name = "BB"       ;Required (do not remove)
command = B, B
time = 10

;-----------recovery-------------

[Command]
name = "recovery" ;Required (do not remove)
command = x+y
time = 1

;-----------Normals-------------

[Command]
name = "a"
command = a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "start"
command = s
time = 1

;-----------Hold-------------

[Command]
name = "holdfwd"  ;Required (do not remove)
command = /$F
time = 1

[Command]
name = "holdback" ;Required (do not remove)
command = /$B
time = 1

[Command]
name = "holdup"   ;Required (do not remove)
command = /$U
time = 1

[Command]
name = "holddown" ;Required (do not remove)
command = /$D
time = 1

[Command]
name = "holdz"
command = /z
time = 1

[Command]
name = "holdc"
command = /c
time = 1

;-----------Directions-------------

[Command]
name = "fwd"
command = F
time = 1

[Command]
name = "back"
command = B
time = 1

[Command]
name = "up"
command = U
time = 1

[Command]
name = "down"
command = D
time = 1

[Statedef -1]

;------------------------------------------------
; AI switch -> ON
[State -1, Activate AI]
type = Varset
triggerall = var(59) != 1
trigger1 = command = "CPU1"
trigger2 = command = "CPU2"
trigger3 = command = "CPU3"
trigger4 = command = "CPU4"
trigger5 = command = "CPU5"
trigger6 = command = "CPU6"
trigger7 = command = "CPU7"
trigger8 = command = "CPU8"
trigger9 = command = "CPU9"
trigger10 = command = "CPU10"
trigger11 = command = "CPU11"
trigger12 = command = "CPU12"
trigger13 = command = "CPU13"
trigger14 = command = "CPU14"
trigger15 = command = "CPU15"
trigger16 = command = "CPU16"
trigger17 = command = "CPU17"
trigger18 = command = "CPU18"
trigger19 = command = "CPU19"
trigger20 = command = "CPU20"
trigger21 = command = "CPU21"
trigger22 = command = "CPU22"
trigger23 = command = "CPU23"
trigger24 = command = "CPU24"
trigger25 = command = "CPU25"
trigger26 = command = "CPU26"
trigger27 = command = "CPU27"
trigger28 = command = "CPU28"
trigger29 = command = "CPU29"
trigger30 = command = "CPU30"
trigger31 = command = "CPU31"
trigger32 = command = "CPU32"
trigger33 = command = "CPU33"
trigger34 = command = "CPU34"
trigger35 = command = "CPU35"
trigger36 = command = "CPU36"
trigger37 = command = "CPU37"
trigger38 = command = "CPU38"
trigger39 = command = "CPU39"
trigger40 = command = "CPU40"
trigger41 = command = "CPU41"
trigger42 = command = "CPU42"
trigger43 = command = "CPU43"
trigger44 = command = "CPU44"
trigger45 = command = "CPU45"
trigger46 = command = "CPU46"
trigger47 = command = "CPU47"
trigger48 = command = "CPU48"
trigger49 = command = "CPU49"
trigger50 = command = "CPU50"
trigger51 = command = "CPU51"
trigger52 = command = "CPU52"
trigger53 = command = "CPU53"
trigger54 = command = "CPU54"
trigger55 = command = "CPU55"
trigger56 = command = "CPU56"
trigger57 = command = "CPU57"
trigger58 = command = "CPU58"
trigger59 = command = "CPU59"
trigger60 = command = "CPU60"
trigger61 = command = "CPU61"
trigger62 = command = "CPU62"
trigger63 = command = "CPU63"
v = 59
value = 1

;------------------AI----------------------

;guarding AI
[State -1, StandguardAI]
type = ChangeState
value = 130
;triggerall = roundstate = 2
triggerall = var(59) = 1
triggerall = p2movetype = A ;<------- Trigger when opponent attacking
triggerall = p2bodydist x = [-700,700] ;<--- Trigger when the opponent is between 0 to 40 pixels away horizontaly
;triggerall = p2bodydist X >= 11
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
triggerall = random < 300 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype = S
triggerall = movetype != H
triggerall = StateNo != [800,899]
trigger1 = ctrl =1

;guarding AI
[State -1, crouchguard2AI]
type = ChangeState
value = 131
;triggerall = roundstate = 2
triggerall = var(59) = 1
triggerall = p2movetype = A ;<------- Trigger when opponent attacking
triggerall = p2bodydist x = [-700,700] ;<--- Trigger when the opponent is between 0 to 40 pixels away horizontaly
;triggerall = p2bodydist X >= 11
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
triggerall = random < 300 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype = C
triggerall = movetype != H
triggerall = StateNo != [800,899]
trigger1 = ctrl =1

;Air Guarding AI
[State -1, Airguard3AI]
type = ChangeState
value = 132
;triggerall = roundstate = 2
triggerall = var(59) = 1
triggerall = p2movetype = A ;<------- Trigger when opponent attacking
triggerall = p2bodydist x = [-700,700] ;<--- Trigger when the opponent is between 0 to 40 pixels away horizontaly
;triggerall = p2bodydist X >= 11
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
triggerall = random < 300 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype = A
triggerall = movetype != H
triggerall = StateNo != [800,899]
trigger1 = ctrl =1

;---------------------------------------------------------------------------
;Hyper Breath (throw) AI
[State -1, ThrowHyperBreathAI]
type = ChangeState
triggerall = PalNo !=5
triggerall = PalNo !=6
value = 800
triggerall = statetype != A
triggerall = ctrl
triggerall = stateno != 100
triggerall = var(59) = 1
triggerall = random < 90
triggerall = P2BodyDist Y = [-5, 30]
triggerall = p2bodydist X <16
triggerall = (p2statetype = S) || (p2statetype = C)
triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;Electric Breath (throw) AI
[State -1, ThrowElectricBreathAI]
type = ChangeState
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
value = 810
triggerall = statetype != A
triggerall = ctrl
triggerall = stateno != 100
triggerall = var(59) = 1
triggerall = random < 90
triggerall = P2BodyDist Y = [-5, 30]
triggerall = p2bodydist X <16
triggerall = (p2statetype = S) || (p2statetype = C)
triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------
;Run Fwd AI
[State -1, RunFwdAI]
type = ChangeState
value = 100
triggerall = var(59) = 1
triggerall = p2bodydist x > 50
triggerall = random < 10
triggerall = P2Life != 0
triggerall = statetype = S
triggerall = movetype != H
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------
;Hop Back AI
[State -1, Hop BackAI]
type = ChangeState
value = 105
triggerall = var(59) = 1
triggerall = p2bodydist x < 60
triggerall = random < 10
triggerall = P2Life != 0
triggerall = statetype = S
triggerall = movetype != H
triggerall = BackEdgeDist > 20
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------
;Walk Backwards AI
[State -1, WalkBackwardsAI]
type = ChangeState
value = 21
triggerall = var(59) = 1
triggerall = p2bodydist x < 200
triggerall = random < 50
triggerall = BackEdgeDist > 20
triggerall = statetype = S
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------
;Crouching AI
[State -1, CrouchingAI]
type = ChangeState
value = 13
triggerall = var(59) = 1
triggerall = p2bodydist x < 200
triggerall = random < 40
;trigger1 = command = "FF"
triggerall = statetype = S
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand Light Punch AI
[State -1, StandLightPunchAI]
type = ChangeState
value = 200
triggerall = statetype != A
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = random < 60
triggerall = p2bodydist X <= 60
triggerall = p2bodydist y = [-10,5]
triggerall = statetype = S
triggerall = movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand Medium Punch AI
[State -1, StandMediumPunchAI]
type = ChangeState
value = 210
triggerall = statetype != A
triggerall = var(59) = 1
triggerall = p2bodydist X <= 60
triggerall = statetype = S
triggerall = random < 60
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact

;---------------------------------------------------------------------------
;Stand Strong Punch AI
[State -1, StandStrongPunchAI]
type = ChangeState
value = 220
triggerall = var(59) = 1
triggerall = statetype = S
triggerall = random < 60
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x = [-5,65]
triggerall = p2bodydist y = [-10,5]
triggerall = movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact

;---------------------------------------------------------------------------
;Stand Light Kick AI
[State -1, StandLightKickAI]
type = ChangeState
value = 230
triggerall = statetype != A
triggerall = var(59) = 1
triggerall = statetype = S
triggerall = random < 60
triggerall = p2bodydist x = [-5,60]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------------------------
;Stand Medium Kick AI
[State -1, StandMediumKickAI]
type = ChangeState
value = 240
triggerall = statetype != A
triggerall = var(59) = 1
triggerall = statetype = S
triggerall = random < 60
triggerall = p2bodydist x = [-2,70]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = movetype != H
triggerall = P2Life > 0
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact

;---------------------------------------------------------------------------
;Standing Strong Kick AI
[State -1, StandingStrongKickAI]
type = ChangeState
value = 250
triggerall = statetype != A
triggerall = var(59) = 1
triggerall = p2bodydist X <= 80
triggerall = statetype = S
triggerall = random < 60
;triggerall = stateno != 100
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact

;---------------------------------------------------------------------------
;Taunt
;[State -1, TauntAI]
;type = ChangeState
;value = 175
;triggerall = var(59) = 1
;triggerall = p2bodydist x = [-800,800]
;triggerall = statetype != A
;triggerall = random < 5
;triggerall = stateno != 100
;trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouching Light Punch AI
[State -1, CrouchingLightPunchAI]
type = ChangeState
value = 400
triggerall = var(59) = 1
triggerall = statetype != A
triggerall = random < 40
triggerall = p2bodydist x = [-5,50]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouching Medium Punch AI
[State -1, CrouchingMediumPunchAI]
type = ChangeState
value = 410
triggerall = var(59) = 1
triggerall = statetype != A
triggerall = random < 40
triggerall = p2bodydist x = [-5,50]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 400 && movecontact
trigger3 = stateno = 430 && movecontact

;---------------------------------------------------------------------------
;Crouching Strong Punch AI
[State -1, CrouchingStrongPunchAI]
type = ChangeState
value = 420
triggerall = var(59) = 1
triggerall = statetype != A
triggerall = random < 40
triggerall = p2bodydist x = [-5,50]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 400 && movecontact || stateno = 410 && movecontact
trigger3 = stateno = 430 && movecontact || stateno = 440 && movecontact

;---------------------------------------------------------------------------
;Crouching Light Kick AI
[State -1, CrouchingLightKickAI]
type = ChangeState
value = 430
triggerall = var(59) = 1
triggerall = statetype != A
triggerall = random < 40
triggerall = p2bodydist x = [-5,50]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;---------------------------------------------------------------------------
;Crouching Medium Kick AI
[State -1, CrouchingMediumKickAI]
type = ChangeState
value = 440
triggerall = var(59) = 1
triggerall = statetype != A
triggerall = random < 40
triggerall = p2bodydist x = [-5,50]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 400 && movecontact
trigger3 = stateno = 430 && movecontact

;---------------------------------------------------------------------------
;Crouching Strong Kick AI
[State -1, CrouchingStrongKickAI]
type = ChangeState
value = 450
triggerall = var(59) = 1
triggerall = statetype != A
triggerall = random < 40
triggerall = p2bodydist x = [-5,50]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-10,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 400 && movecontact || stateno = 410 && movecontact
trigger3 = stateno = 430 && movecontact || stateno = 440 && movecontact

;---------------------------------------------------------------------------
;Jump Light Punch
[State -1, JumpLightPunchAI]
type = ChangeState
value = 600
triggerall = var(59) = 1
triggerall = statetype = A
triggerall = random < 60
triggerall = p2bodydist x = [-5,70]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-20,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno != 1350 ;Air blocking
trigger2 = ctrl

;---------------------------------------------------------------------------
;Jump Medium Punch AI
[State -1, JumpMediumPunchAI]
type = ChangeState
value = 610
triggerall = var(59) = 1
triggerall = statetype = A
triggerall = random < 60
triggerall = p2bodydist x = [-5,70]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-20,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno != 1350 ;Air blocking
trigger2 = ctrl
trigger3 = stateno = 600 || stateno = 630 ;jump_x or jump_a
trigger3 = movecontact

;---------------------------------------------------------------------------
;Jump Strong Punch AI
[State -1, JumpStrongPunchAI]
type = ChangeState
value = 620
triggerall = var(59) = 1
triggerall = statetype = A
triggerall = random < 60
triggerall = p2bodydist x = [-5,100]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-20,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 600 || stateno = 610 ;jump_x or jump_a
trigger2 = movecontact
trigger2 = ctrl
trigger3 = stateno != 1350 ;Air blocking
trigger3 = ctrl
trigger4 = stateno = 630 || stateno = 640
trigger4 = movecontact

;---------------------------------------------------------------------------
;Jump Light Kick AI
[State -1, Jump Light KickAI]
type = ChangeState
value = 630
triggerall = var(59) = 1
triggerall = statetype = A
triggerall = random < 60
triggerall = p2bodydist x = [-5,70]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-20,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno != 1350 ;Air blocking
trigger2 = ctrl

;---------------------------------------------------------------------------
;Jump Medium Kick
[State -1, JumpMediumKickAI]
type = ChangeState
value = 640
triggerall = var(59) = 1
triggerall = statetype = A
triggerall = random < 60
triggerall = p2bodydist x = [-5,70]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-20,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 600 || stateno = 630
trigger2 = movecontact
trigger3 = stateno != 1350 ;Air blocking
trigger3 = ctrl

;---------------------------------------------------------------------------
;Jump Strong Kick AI
[State -1, JumpStrongKickAI]
type = ChangeState
value = 650
triggerall = var(59) = 1
triggerall = statetype = A
triggerall = random < 60
triggerall = p2bodydist x = [-5,100]
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist y = [-20,5]
triggerall = P2Life != 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 600 || stateno = 630
trigger2 = movecontact
trigger3 = stateno != 1350 ;Air blocking
trigger4 = stateno = 630 || stateno = 640 ;jump_x or jump_a
trigger4 = movecontact

;---------------------------------------------
;Super Jump AI
[State -1, SuperJumpAI]
type = ChangeState
value = 77337733
triggerall = var(59) = 1
triggerall = random < 10
triggerall = statetype != A
triggerall = P2Life > 0
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl

;Super Jump AI
[State -1, SuperJumpAI]
type = ChangeState
value = 77337733
triggerall = var(59) = 1
triggerall = random < 80
triggerall = statetype != A
triggerall = P2Life > 0
triggerall = movetype = H
triggerall = P2Dist Y <= -20
triggerall = P2BodyDist X = [-5,75]
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 220 && movecontact

;---------------------------------------------
;Soaring Justice 1
[State -1, SoaringJusticeAI]
type = ChangeState
value = 1400
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X <= 200
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;---------------------------------------------
;Super Speed weak
[State -1, SuperSpeed1AI]
type = ChangeState
value = 1530
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X <= 300
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;---------------------------------------------
;Super Speed medium
[State -1, SuperSpeed2AI]
type = ChangeState
value = 1500
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X <= 350
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;---------------------------------------------
;Super Speed 3
[State -1, SuperSpeed3AI]
type = ChangeState
value = 1520
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X <= 400
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;---------------------------------------------
;Heat Vision 1
[State -1, HeatVision1AI]
type = ChangeState
value = 1000
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;Electric Vision 1
[State -1, ElectricVisionWeakAI]
type = ChangeState
value = 1002
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;Cosmic Burst
[State -1, CosmicBurstAI]
type = ChangeState
value = 1016
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X = [-2,120]
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;Cosmic Beam 1
[State -1, CosmicBeamAI]
type = ChangeState
value = 1025
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;---------------------------------------------
;Heat Vision 2
[State -1, HeatVision2AI]
type = ChangeState
value = 1005
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;---------------------------------------------
;Air Heat Vision 3
[State -1, AirHeatVision3AI]
type = ChangeState
value = 1010
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 20
triggerall = statetype = A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 600 && movecontact
trigger3 = stateno = 630 && movecontact
trigger4 = stateno = 610 && movecontact
trigger5 = stateno = 640 && movecontact

;Air Cosmic Beam
[State -1, AirCosmicBeamAI]
type = ChangeState
value = 1015
triggerall = PalNo = 12
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 20
triggerall = statetype = A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 600 && movecontact
trigger3 = stateno = 630 && movecontact
trigger4 = stateno = 610 && movecontact
trigger5 = stateno = 640 && movecontact

;Air Heat Vision Cosmic Alt
[State -1, AirHeatVisionCosmicAltAI]
type = ChangeState
value = 1010
triggerall = PalNo = 12
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X >= 20
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 20
triggerall = statetype = A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 600 && movecontact
trigger3 = stateno = 630 && movecontact
trigger4 = stateno = 610 && movecontact
trigger5 = stateno = 640 && movecontact

;--------------------------------------------
;Up in the air, it's a bird, it'sa plane, no it's Superman!
[State -1, UpInTheAirAI]
type = ChangeState
value = 3700
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X = [-2,300]
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 90
triggerall = P2BodyDist Y = [-60, 45]
triggerall = statetype = A
triggerall = movetype != H
triggerall = power >=1000
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact
trigger8 = stateno = 1401 && movecontact
trigger9 = stateno = 1402 && movecontact
trigger10 = stateno = 1403 && movecontact

;---------------------------------------------
;Solar Flare
[State -1, SolarFlareAI]
type = ChangeState
value = 1200
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X = [-20,170]
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
;triggerall = power >=200
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
triggerall = Life <=100
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;Air Solar Flare
[State -1, AirSolarFlareAI]
type = ChangeState
value = 1210
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X = [-20,130]
;triggerall = p2statetype != A ;<------- Trigger when the opponent is not in air
;triggerall = p2movetype != H
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype = A
triggerall = movetype != H
;triggerall = power >=200
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
triggerall = Life <=100
trigger1 = ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;---------------------------------------------
;Cold Breath Ice Patch
[State -1, ColdBreathIcePatchAI]
type = ChangeState
value = 1300
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X = [-20,170]
triggerall = numhelper(1301) = 0
triggerall = numhelper(1302) = 0
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;Cold Breath Freeze AI
[State -1, ColdBreathFreezeAI]
type = ChangeState
value = 1310
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist X = [-20,170]
triggerall = numhelper(1130) = 0
triggerall = P2Life > 0
triggerall = random < 10
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger3 = stateno = 230 && movecontact
trigger4 = stateno = 210 && movecontact
trigger5 = stateno = 240 && movecontact
trigger6 = stateno = 250 && movecontact
trigger7 = stateno = 220 && movecontact

;-----------------------------------
;Hyper Kryptonian Crusher AI
[State -1, HyperKryptonianCrusherAI]
type = ChangeState
value = 3000
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x < 350 ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 50 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Meteor Smasher AI
[State -1, HyperMeteorSmasherAI]
type = ChangeState
value = 3400
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x < 200 ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 50 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 400 && movecontact
trigger9 = Stateno = 410 && movecontact
trigger10 = Stateno = 420 && movecontact
trigger11 = Stateno = 430 && movecontact
trigger12 = Stateno = 440 && movecontact
trigger13 = Stateno = 450 && movecontact

;Hyper Heat Vision AI
[State -1, HyperHeatVisionAI]
type = ChangeState
value = 3500
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x = [-2,400] ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 20 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Electro Magnetic Blast AI
[State -1, HyperElectroMagneticBlastAI]
type = ChangeState
value = 3550
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x = [-2,400] ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 20 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Power Cosmic Blast AI
[State -1, HyperPowerCosmicBlastAI]
type = ChangeState
value = 3555
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x = [-2,400] ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 20 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Electric Fists AI
[State -1, HyperElectricFistAI]
type = ChangeState
value = 3450
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x < 350 ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 50 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Faster Than A Speeding Bullet AI
[State -1, HyperFasterThanSpeedingBulletAI]
type = ChangeState
value = 3720
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
;triggerall = p2bodydist x < 350 ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 50 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Frost Breath AI
[State -1, HyperFrostBreathAI]
type = ChangeState
value = 3630
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = power >=1000
triggerall = P2Life > 0
triggerall = var(59) = 1
triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
;triggerall = p2bodydist x < 350 ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 50 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Solar Annihilation AI
[State -1, HyperSolarAnnihilationAI]
type = ChangeState
value = 3800
triggerall = power >=1000
triggerall = P2Life != 0
triggerall = var(59) = 1
;triggerall = p2statetype != L ;<------- Trigger when opponent is not lying on the floor
triggerall = p2bodydist x < 200 ;<--- Trigger when the opponent is Grater Than 50 pixels away horizontaly
;triggerall = p2statetype = S || p2statetype = C ;<------- Trigger when the opponent is not in air
triggerall = random < 90 ;<---------- Trigger the move in 50% of the times the conditions is met (i'll explain more)
triggerall = statetype != A
triggerall = movetype != H
triggerall = stateno != [1000,3999]
triggerall = P2StateNo != 5100
triggerall = P2StateNo != 5110
triggerall = P2StateNo != 5150
triggerall = StateNo != [800,899]
triggerall = Life <=100
trigger1 = ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;------------^^^^^^^---AI---^^^^^^^------------

;--------------------Hypers--------------------

;Meteor Smasher
[State -1, MeteorSmasher]
type = ChangeState
value = 3400
triggerall = Command = "MeteorSmasher"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 215 && movecontact
trigger9 = Stateno = 400 && movecontact
trigger10 = Stateno = 410 && movecontact
trigger11 = Stateno = 420 && movecontact
trigger12 = Stateno = 430 && movecontact
trigger13 = Stateno = 440 && movecontact
trigger14 = Stateno = 450 && movecontact

;Kryptonian Crusher
[State -1, KryptonianCrusher]
type = ChangeState
value = 3000
triggerall = Command = "KryptonianCrusher"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 215 && movecontact

;Solar Annihilation
[State -1, SolarAnnihilation]
type = ChangeState
value = 3800
triggerall = Command = "SolarAnnihilation"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
triggerall = Life <=100
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 215 && movecontact
trigger9 = Stateno = 400 && movecontact
trigger10 = Stateno = 410 && movecontact
trigger11 = Stateno = 420 && movecontact
trigger12 = Stateno = 430 && movecontact
trigger13 = Stateno = 440 && movecontact
trigger14 = Stateno = 450 && movecontact

;Up in the Clouds! It's a Bird! It's a plane! No, It's Superman!
[State -1, HyperUpInTheClouds]
type = ChangeState
value = 3700
triggerall = Command = "UpInTheClouds"
triggerall = var(59) != 1
triggerall = StateType = A
triggerall = Power >= 1000
trigger1 = Ctrl = 1
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 630 && movecontact
trigger4 = Stateno = 610 && movecontact
trigger5 = Stateno = 640 && movecontact
trigger6 = stateno = 1401 && movecontact
trigger7 = stateno = 1402 && movecontact
trigger8 = stateno = 1403 && movecontact

;Hyper Heat Vision
[State -1, HyperHeatVision]
type = ChangeState
value = 3500
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
triggerall = Command = "HyperHeatVision"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 215 && movecontact

;Hyper Electro Magnetic Blast
[State -1, HyperElectroMagneticBlast]
type = ChangeState
value = 3550
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
triggerall = Command = "HyperHeatVision"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 215 && movecontact

;Hyper Power Cosmic Blast
[State -1, HyperPowerCosmicBlast]
type = ChangeState
value = 3555
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = Command = "HyperHeatVision"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 215 && movecontact

;Hyper Electric Fists
[State -1, HyperElectricFists]
type = ChangeState
value = 3450
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
triggerall = Command = "UpInTheClouds"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Faster Than a Speeding Bullet
[State -1, HyperFasterThanSpeedingBullet]
type = ChangeState
value = 3720
triggerall = Command = "FasterThanSpeedingBullet"
triggerall = Power >= 1000
triggerall = var(59) != 1
triggerall = StateType != A
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Hyper Freeze Breath
[State -1, HyperFreezeBreath]
type = ChangeState
value = 3630
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = Command = "UpInTheClouds"
triggerall = var(59) != 1
triggerall = StateType !=A
triggerall = Power >= 1000
trigger1 = Ctrl = 1
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;--------------Specials----------------------

;Soaring Justice
[State -1, SoaringJustice]
type = ChangeState
value = 1400
triggerall = Command = "SoaringJustice" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 400 && movecontact
trigger9 = Stateno = 410 && movecontact
trigger10 = Stateno = 420 && movecontact
trigger11 = Stateno = 430 && movecontact
trigger12 = Stateno = 440 && movecontact
trigger13 = Stateno = 450 && movecontact

;--------------------------------------------
;Super Speed weak
[State -1, SuperSpeed1]
type = ChangeState
value = 1530
triggerall = Command = "SuperSpeed" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 400 && movecontact
trigger9 = Stateno = 410 && movecontact
trigger10 = Stateno = 420 && movecontact
trigger11 = Stateno = 430 && movecontact
trigger12 = Stateno = 440 && movecontact
trigger13 = Stateno = 450 && movecontact

;--------------------------------------------
;Super Speed medium
[State -1, SuperSpeed2]
type = ChangeState
value = 1500
triggerall = Command = "SuperSpeed2" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 400 && movecontact
trigger9 = Stateno = 410 && movecontact
trigger10 = Stateno = 420 && movecontact
trigger11 = Stateno = 430 && movecontact
trigger12 = Stateno = 440 && movecontact
trigger13 = Stateno = 450 && movecontact

;--------------------------------------------
;Super Speed strong
[State -1, SuperSpeed3]
type = ChangeState
value = 1520
triggerall = Command = "SuperSpeed3" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 400 && movecontact
trigger9 = Stateno = 410 && movecontact
trigger10 = Stateno = 420 && movecontact
trigger11 = Stateno = 430 && movecontact
trigger12 = Stateno = 440 && movecontact
trigger13 = Stateno = 450 && movecontact

;--------------------------------------------
;Heat Vision 1
[State -1, HeatVision1]
type = ChangeState
value = 1000
triggerall = Command = "HeatVision1" && StateType != A
triggerall = var(59) != 1
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Electric Vision weak
[State -1, ElectricVisionWeak]
type = ChangeState
value = 1002
triggerall = Command = "HeatVision1" && StateType != A
triggerall = var(59) != 1
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Cosmic Burst weak
[State -1, CosmicBurstWeak]
type = ChangeState
value = 1016
triggerall = Command = "HeatVision1" && StateType != A
triggerall = var(59) != 1
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Heat Vision 2
[State -1, HeatVision2]
type = ChangeState
value = 1005
triggerall = Command = "HeatVision2" && StateType != A
triggerall = var(59) != 1
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Heat Vision 3
[State -1, HeatVision3]
type = ChangeState
value = 1005
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=12
triggerall = Command = "HeatVision3" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Cosmic Beam
[State -1, CosmicBeam]
type = ChangeState
value = 1025
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = Command = "HeatVision2" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Cosmic Beam
[State -1, CosmicBeam]
type = ChangeState
value = 1005
triggerall = PalNo = 12
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = Command = "HeatVision3" && StateType != A
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Air Heat Vision 1
[State -1, AirHeatVision1]
type = ChangeState
value = 1010
triggerall = PalNo !=12
triggerall = StateType = A && Command = "HeatVision1"
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;Air Heat Vision 2
[State -1, AirHeatVision2]
type = ChangeState
value = 1010
triggerall = PalNo !=12
triggerall = StateType = A && Command = "HeatVision2"
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;Air Heat Vision 3
[State -1, AirHeatVision3]
type = ChangeState
value = 1010
triggerall = PalNo !=12
triggerall = StateType = A && Command = "HeatVision3"
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;Air Cosmic Beam
[State -1, AirCosmicBeam]
type = ChangeState
value = 1015
triggerall = PalNo = 12
triggerall = StateType = A && Command = "HeatVision1"
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;Air Cosmic Beam
[State -1, AirCosmicBeam]
type = ChangeState
value = 1015
triggerall = PalNo = 12
triggerall = StateType = A && Command = "HeatVision2"
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;Air Cosmic Beam
[State -1, AirCosmicBeam]
type = ChangeState
value = 1010
triggerall = PalNo = 12
triggerall = StateType = A && Command = "HeatVision3"
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;--------------------------------------------
;Solar Flare
[State -1, SolarFlare]
type = ChangeState
value = 1200
triggerall = StateType != A && Command = "SolarFlare"
triggerall = var(59) != 1
triggerall = Life <=100
;triggerall = Power >= 200
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact
trigger8 = Stateno = 400 && movecontact
trigger9 = Stateno = 410 && movecontact
trigger10 = Stateno = 420 && movecontact
trigger11 = Stateno = 430 && movecontact
trigger12 = Stateno = 440 && movecontact
trigger13 = Stateno = 450 && movecontact

;Air Solar Flare
[State -1, AirSolarFlare]
type = ChangeState
value = 1210
triggerall = StateType = A && Command = "SolarFlare"
triggerall = var(59) != 1
triggerall = StateType != S || StateType != C
triggerall = Life <=100
;triggerall = Power >= 200
trigger1 = Ctrl
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 610 && movecontact
trigger4 = Stateno = 620 && movecontact
trigger5 = Stateno = 630 && movecontact
trigger6 = Stateno = 640 && movecontact
trigger7 = stateno = 650 && movecontact

;--------------------------------------------
;Cold Breath Ice Patch
[State -1, ColdBreathIcepatch]
type = ChangeState
value = 1300
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = StateType != A && Command = "ColdBreath"
triggerall = var(59) != 1
triggerall = numhelper(1301) = 0
triggerall = numhelper(1302) = 0
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;Cold Breath Freeze
[State -1, ColdBreathFreeze]
type = ChangeState
value = 1310
triggerall = PalNo !=5
triggerall = PalNo !=6
triggerall = StateType != A && Command = "ColdBreath2"
triggerall = var(59) != 1
triggerall = numhelper(1130) = 0
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 220 && movecontact
trigger5 = Stateno = 230 && movecontact
trigger6 = Stateno = 240 && movecontact
trigger7 = Stateno = 250 && movecontact

;--------------throws-----------------------

;Throw - Hyper Breath
[State -1, ThrowHyperBreath]
type = ChangeState
value = 800
triggerall = statetype = S && ctrl = 1 && p2bodydist X < 10 && p2bodydist Y = 0 && Stateno != 100 && p2statetype != A && p2movetype != H
Triggerall = PalNo !=5
Triggerall = PalNo !=6
trigger1 = command = "ThrowHyperBreath" && p2statetype != A

;Throw - Electric Breath
[State -1, ThrowElectricBreath]
type = ChangeState
value = 810
triggerall = PalNo !=1
triggerall = PalNo !=2
triggerall = PalNo !=3
triggerall = PalNo !=4
triggerall = PalNo !=7
triggerall = PalNo !=8
triggerall = PalNo !=9
triggerall = PalNo !=10
triggerall = PalNo !=11
triggerall = PalNo !=12
triggerall = statetype = S && ctrl = 1 && p2bodydist X < 10 && p2bodydist Y = 0 && Stateno != 100 && p2statetype != A && p2movetype != H
trigger1 = command = "ThrowHyperBreath" && p2statetype != A

; Toss backward
;[State -1, Toss Backward]
;type = ChangeState
;value = 800
;triggerall = statetype = S && ctrl = 1 && p2bodydist X < 10 && p2bodydist Y = 0 && Stateno != 100 && p2statetype != A && p2movetype != H
;trigger1 = command = "BackToss" && p2statetype = S
;trigger2 = command = "BackToss" && p2statetype = C

;Air Fireball - Air Throw
;[State -1,Air Throw]
;type = ChangeState
;value = 840
;triggerall = command = "holdfwd"
;triggerall = command = "z"
;triggerall = P2BodyDist X <= 20
;triggerall = P2BodyDist Y = [-6, 42]
;triggerall = ctrl
;;triggerall = var(59) != 1
;trigger1 = statetype = A
;trigger1 = pos Y <= -50
;;trigger1 = Vel X <= 1

;--------------Dash--------------------
; Running Forward
[State -1, Running Forward]
type = ChangeState
value = 100
trigger1 = Command = "FF" && StateType = S && Ctrl = 1 && StateNo != 100 && StateNo != 105
triggerall = var(59) != 1

; Running Back
[State -1, RunBack]
type = ChangeState
value = 105
trigger1 = Command = "BB" && StateType = S && Ctrl = 1 && StateNo != 100 && StateNo != 105
triggerall = var(59) != 1

;----------Other Stuff-------------------------------
;Taunt
[State -1, Taunt]
type = ChangeState
value = 110
triggerall = command = "start"
triggerall = var(59) != 1
trigger1 = statetype != A
trigger1 = ctrl

;movelist
;[State -1, movelist]
;type = ChangeState
;value = 889316
;triggerall = command = "QCB_s"
;trigger1 = statetype != A
;trigger1 = ctrl

;---------------------------------
;Stand Light Punch
[State -1, LightPunch]
type = ChangeState
value = 200
triggerall = Command = "x"
triggerall = Command != "holddown" && StateType = S
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 200 && movecontact && time > 4

;Stand Medium Punch
[State -1, MediumPunch]
type = ChangeState
value = 210
triggerall = Command = "y" && Command != "holddown" && StateType = S
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 230 && movecontact

;Stand Hard Punch
[State -1, StrongPunch]
type = ChangeState
value = 220
triggerall = Command = "z" && Command != "holddown" && StateType = S
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 230 && movecontact
trigger5 = Stateno = 240 && movecontact

;--------------------------
;Stand Light Kick
[State -1, LightKick]
type = ChangeState
value = 230
triggerall = Command = "a" && Command != "holddown" && StateType = S
triggerall = var(59) != 1
trigger1 = Ctrl

;Stand Medium Kick
[State -1, MediumKick]
type = ChangeState
value = 240
triggerall = Command = "b" && Command != "holddown" && StateType = S
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 230 && movecontact

; Stand Hard Kick
[State -1, StrongKick]
type = ChangeState
value = 250
triggerall = Command = "c" && Command != "holddown" && StateType = S
triggerall = var(59) != 1
trigger1 = Ctrl
trigger2 = Stateno = 200 && movecontact
trigger3 = Stateno = 210 && movecontact
trigger4 = Stateno = 230 && movecontact
trigger5 = Stateno = 240 && movecontact

;--------------------------
; Crouch Light Punch
[State -1, Crouch Light Punch]
type = ChangeState
value = 400
triggerall = Command = "x" && Command = "holddown" && StateType = C
triggerall = var(59) != 1
trigger1 = Ctrl = 1

; Crouch Medium Punch
[State -1, Crouch Medium Punch]
type = ChangeState
value = 410
triggerall = Command = "y" && Command = "holddown" && StateType = C
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 400 && movecontact
trigger3 = Stateno = 430 && movecontact

; Crouch Hard Punch
[State -1, Crouch Hard Punch]
type = ChangeState
value = 420
triggerall = Command = "z" && Command = "holddown" && StateType = C
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 400 && movecontact
trigger3 = Stateno = 410 && movecontact
trigger4 = Stateno = 430 && movecontact
trigger5 = Stateno = 440 && movecontact

; Crouch Light Kick
[State -1, Crouch Light Kick]
type = ChangeState
value = 430
triggerall = Command = "a" && Command = "holddown" && StateType = C
triggerall = var(59) != 1
trigger1 = Ctrl = 1

; Crouch Medium Kick
[State -1, Crouch Medium Kick]
type = ChangeState
value = 440
triggerall = Command = "b" && Command = "holddown" && StateType = C
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 400 && movecontact
trigger3 = Stateno = 430 && movecontact

; Crouch Hard Kick
[State -1, Crouch Hard Kick]
type = ChangeState
value = 450
triggerall = Command = "c" && Command = "holddown" && StateType = C
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 400 && movecontact
trigger3 = Stateno = 410 && movecontact
trigger4 = Stateno = 430 && movecontact
trigger5 = Stateno = 440 && movecontact

;--------------------------
; Jump Light Punch
[State -1, Jump Light Punch]
type = ChangeState
value = 600
triggerall = Command = "x" && StateType = A
triggerall = var(59) != 1
trigger1 = Ctrl = 1

; Jump Medium Punch
[State -1, Jump Medium Punch]
type = ChangeState
value = 610
triggerall = Command = "y" && StateType = A
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 630 && movecontact

; Jump Hard Punch
[State -1, Jump Hard Punch]
type = ChangeState
value = 620
triggerall = Command = "z" && StateType = A
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 630 && movecontact
trigger4 = Stateno = 610 && movecontact
trigger5 = Stateno = 640 && movecontact

; Jump Light Kick
[State -1, Jump Light Kick]
type = ChangeState
value = 630
triggerall = Command = "a" && StateType = A
triggerall = var(59) != 1
trigger1 = Ctrl = 1

; Jump Medium Kick
[State -1, Jump Medium Kick]
type = ChangeState
value = 640
triggerall = Command = "b" && StateType = A
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 630 && movecontact

; Jump Hard Kick
[State -1, Jump Hard Kick]
type = ChangeState
value = 650
triggerall = Command = "c" && StateType = A
triggerall = var(59) != 1
trigger1 = Ctrl = 1
trigger2 = Stateno = 600 && movecontact
trigger3 = Stateno = 630 && movecontact
trigger4 = Stateno = 610 && movecontact
trigger5 = Stateno = 640 && movecontact

;--------------------------------------------------
[State -1, SuperJump]
type = ChangeState
value = 77337733
triggerall = var(59) != 1
trigger1 = command = "DU"
trigger1 = ctrl ; these means that you can make the move when you control the char
trigger1 = statetype != A ; these is to make that you cant use the superjump while you are in the air
; If you want to make a launcher you can use these
trigger2 = (stateno = 421 || stateno = 9808) && (movehit) && (command = "holdup") ;y
; Final Update!

;--------------------------------------------------
; Recovery roll code by DavidGee Mugen Fighters Guild code snippet

[State -1]
type = VarSet
trigger1 = (Var(3) = 0) && (MoveType = H) && (command = "Roll")
v = 0
value = 1

[State -1]
type = VarSet
trigger1 = ((Var(3) = 1) && (MoveType != H)) || (Lose)
v = 0
value = 0
